checking for errors
Kidd254/Portfolio-setup-and-mobile-first pull request #1
Opened 2022-09-22 10:06 UTC by Kidd254

2022-09-22 10:26 UTC, emmiiorji requested changes
Hi @Kidd254, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that has no pull request description and a title not descriptive enough. Kindly always provide adequate PR title and description for your PRs in order to make it easier to know the changes applied at a glance.

Also, you seem to have made most of your changes to the main branch instead of a feature branch as recommended for GitHub flow. Kindly make sure that your PR contains all the changes made in the milestone in order to allow for a reviewer to make comments on the changes.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-23 10:32 UTC, Nyame-Wolf requested changes
# STATUS: REQUIRED CHANGES :recycle: 

Hi @Kidd254  :wave: 

Your project page is looking fantastic so far :star_struck: ! 

However, there is still some room for improvement, that can help you have better code and make your project professional :sunglasses: 

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights :sparkles:

- Great work using the right GitHub Flow :100: 
- Great work using the same font as Figma design ☑️ 
- Commits are descriptive and meaningful :+1: 
- Project Documentation (PR, README) is professional :necktie: 

Congrats on your work so far! :clap:  

## Required Changes ♻️

- [ ] Kindly note that your submission does not meet figma template requirements. has a fixed width and height and should not It also has margins that are not similar to the figma template's
- [ ] Your design
<img width="855" alt="Screenshot 2022-09-23 at 13 25 24" src="https://user-images.githubusercontent.com/48546992/191942365-1ba67434-c64f-4b74-b097-5c1f741cb748.png">

- [ ] Figma template:
<img width="905" alt="Screenshot 2022-09-23 at 12 35 53" src="https://user-images.githubusercontent.com/48546992/191942512-d9010f42-b3c2-45c6-b406-5f3d5ff1fc9d.png">

Please match the design.

 

There are some issues that you still need to work on to go to the next project, but you are almost there! 
_For more information, check the comments under the review :arrow_down:_

## Optional suggestions :ballot_box_with_check: 

_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code :100:_

Happy coding and keep it up! :raised_hands: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
  Please, remember to tag me **@Nyame-Wolf**  in your question so I can receive the notification.

  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

  _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-09-23 10:32 UTC, Nyame-Wolf commented on index.html
> -<div class="header">I'm Lawrence Glad to see you</div>
Kindly use a `<h1>` element for the line I'm Lawrence
then use `<h2>` or any other header tags.

The div element is too general and this header is  used for the title of your file.
You can read more [here](https://www.reliablesoft.net/h1-tag/)

2022-09-23 10:32 UTC, Nyame-Wolf commented on index.html
> +
Please have all this in the css file.

2022-09-23 10:32 UTC, Nyame-Wolf commented on index.html
> +            <h1 class="logo"> My Logo </h1>
Kindly note that this should be a link to use an anchor element. 
This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2022-09-23 10:32 UTC, Nyame-Wolf commented on index.html
> +            </div>
Kindly note that this should use links. `<ul>` and `<li>`
Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href.

2022-09-23 10:32 UTC, Nyame-Wolf commented on index.html
> -    </svg>
This is a tremendous job you have done setting up your the background images. You have used the inline styles for the shapes. I recommend using the css file for all the css related information. Read [here](https://www.hostinger.com/tutorials/difference-between-inline-external-and-internal-css#:~:text=Advantages%20of%20External%20CSS%3A,css%20file%20for%20multiple%20pages.) why this is the recommended format

2022-09-23 10:32 UTC, Nyame-Wolf commented on index.html
> -</body>
This should appear at the end of the page, just before the closing `<html>` tag

2022-09-23 10:32 UTC, Nyame-Wolf commented on index.html
> +    <div class="background">
Please use a `<section>` tag here.
It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info.

2022-09-24 09:34 UTC, emmiiorji approved these changes
Hi @Kidd254, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congratulations](https://user-images.githubusercontent.com/20554583/192091020-22d99977-a6dd-483a-9d5d-6ddca2edb55f.gif)


## Good Highlights✔

- Adherence to GitHub flow
- Good commit messages
- Requested changes have been implemented

## Optional suggestions

- I suggest that you endeavor to always provide a description to your PR in order tell at a glance what changes has occurred.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-27 08:38 UTC, merged