Pair contactform
Kidd254/Portfolio-setup-and-mobile-first pull request #5
Opened 2022-10-04 13:25 UTC by Kidd254

in this branch I modified the html and the css file

2022-10-04 14:21 UTC, Nemwel-Boniface requested changes
## Hello @Kidd254      :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Great job working on your portfolio so far! :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-04 14:21 UTC, Nemwel-Boniface commented on index.html
>  </body>
- [ ] Great job working on your portfolio contact form. There is a white space that appears immediately below the contact form which is not supposed to be there according to the Figma design. Kindly ensure that you trim the white space an have the contact form as the last thing to meet all the project requirements. 

**This is how I am seeing the design right now:**

![image](https://user-images.githubusercontent.com/86318284/193842728-b76327c9-2ddf-4029-b9ce-744bed97ea3a.png)

**This is the desired design:**

![image](https://user-images.githubusercontent.com/86318284/193842825-4de485fa-c6b4-482a-8494-0f662aa375c8.png)

2022-10-04 15:38 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @Kidd254, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - No linter errors. ✔️
 - Professional PR. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] As the previous code reviewer mentioned, there is a whitespace at the bottom of your portfolio. This whitespace is due to a fixed height attribute that you added to a `.all` class that is applied to a `div` tag that is around the whole portfolio. Kindly remove this fixed height to make your portfolio fit on the mobile screen with a better UI.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

 - [OPTIONAL] Your portfolio also has a `.background` class with a fixed width higher than any mobile screen width, making a horizontal scroll possible and a bad user experience. It would be nice if this fixed width is removed from that class. Fixed values can mess with the responsiveness of pages if not well applied.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-05 08:15 UTC, Nemwel-Boniface approved these changes
## Hello @Kidd254          :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making the changes I requested good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-05 15:38 UTC, merged